// src/lib/build-meta.ts
// Auto-generated by scripts/set-build-meta.mjs. Do not edit manually.

export const BUILD_META = {
  commit: '34e98d7',
  generatedAt: '2026-03-12T11:09:14.494Z',
} as const;
