// src/lib/build-meta.ts
// Auto-generated by scripts/set-build-meta.mjs. Do not edit manually.

export const BUILD_META = {
  commit: '7ee86b7',
  generatedAt: '2026-03-12T10:43:58.091Z',
} as const;
