// src/lib/build-meta.ts
// Auto-generated by scripts/set-build-meta.mjs. Do not edit manually.

export const BUILD_META = {
  commit: '834c9e3',
  generatedAt: '2026-03-12T06:05:20.972Z',
} as const;
